// <auto-generated />
namespace BikeStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class orders_products_order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orders_products_order));
        
        string IMigrationMetadata.Id
        {
            get { return "201809240823220_orders_products_order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
